name: Generate ASCII Artwork

on:
  push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: List repo files
          run: ls -ltra
        - name: Execute shell scripting
          run: ./ascii-script.sh
       